defaults:
    - override hydra/launcher: submitit_local

# environment
# task: dog-run
# task: humanoid-stand
# task: reacher-hard
task: pointmass-easy

device: cuda
# device: mps

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 2500
num_videos: 3

# training
# steps: 10_000_000
steps: 50_000
updates_per_step: 0.1
batch_size: 1024
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: false
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 6
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# control
control: true
lr_ctrl_pi: 0. #5e-3
lr_ctrl_dyn: 5e-3
# ctrl_update_steps: 10

# fixed eval run
init_state: [-0.2, -0.2,  0.,  0.]
# target: [0.1, 0.1] # ang, radius
target: [0.8, 0.2] # ang, radius
target_size: 0.01
target_margin: 0.1

# perturbation
perturb: true
perturb_steps: 5000
perturb_scale: 0. # 0.6
action_noise: 0.2
action_skip: 20
obs_noise: 0.2

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 0
no_enc: true
num_enc_layers: 2
enc_dim: 256
mlp_dim: 512
# latent_dim: 512
latent_dim: 4
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 4 #8

# logging
wandb_project: control
wandb_entity: cstein06
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: 500
bin_size: ???
