defaults:
    - override hydra/launcher: submitit_local

# environment
# task: dog-run
# task: humanoid-stand
# task: reacher-hard
task: pointmass-mine

device: cuda
# device: mps


# evaluation
# checkpoint: ???
eval_episodes: 3
eval_freq: 2500
num_videos: 3

# training
# steps: 10_000_000
steps: 50_000
updates_per_step: 1.
batch_size: 512
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: false
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 6
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# fixed eval run
# init_state: [-0.2, -0.2,  0.,  0.]

init_state: [-0.2, 0.,  0.,  0.]

# target: [0.1, 0.1] # ang, radius
target: [0.2, 0.2] # x, y

friction: 0. # not sure this works. change 'damping' in pointmass.xml

target_size: 0.02
target_margin: 0.6 #0.3
control_cost: 1. #0.1
target_reward: 1.
control_norm_thres: 0. #0.4

terminate_at_target: false #true
target_end_dist: 0.02
# target_margin: 0. 
end_reward: null

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 0

no_enc: true
num_enc_layers: 2
enc_dim: 256

action_repeat: 2

episode_length: 200 # 500

################ pre train ######## 

perturb: true
perturb_steps: -1
perturb_scale: 0.
action_noise: 0.1
action_skip: 0
obs_noise: 0.

force_field: false
force_field_scale: 5.

action_limit: true

# control
seed_steps: 2500
control: true 
ctrl_mse: false
ctrl_horizon: 8

lr_ctrl_pi: 0. #1e-4
lr_ctrl_dyn: 5e-4
pi_lr: 3e-4
lr: 3e-4
train_agent: true
seed_random: false

########### perturbation test ###########

# perturb: true
# perturb_steps: 20000
# perturb_scale: 0.5 #0.5 
# action_noise: 0. # 0.1
# action_skip: 0 # 20
# obs_noise: 0. # 0.01

# force_field: false
# # force_field_scale: 5.

# action_limit: false

# # control
# seed_steps: 2500
# control: true
# # control: false
# ctrl_mse: true #false
# ctrl_horizon: 8

# lr_ctrl_pi: 4e-3
# lr_ctrl_dyn: 0.
# pi_lr: 0.
# lr: 0.
# train_agent: false
# seed_random: false

########################

ctrl_sig_init: 0.02
# lr_ctrl_dyn_hidden: 1e-5
# lr_ctrl_dyn_last: 10e-5
# ctrl_update_steps: 10

fixed_init_state: false
# num_ctrl_layers: 1
# ctrl_dim: 256
num_ctrl_layers: 2
ctrl_dim: 512

mlp_dim: 512
# latent_dim: 512
latent_dim: 4

action_arrow_scale: 0.02
dist_range: 100

# checkpoint_wandb: false
# checkpoint_wandb: 'cstein06/control/pointmass-easy-default-1-final:v19'
# checkpoint_wandb: 'cstein06/control/pointmass-easy-default-charmed-fire-181-final:v0'
# checkpoint_wandb: 'cstein06/control/pointmass-easy-default-charmed-firefly-361-final:v0'
# checkpoint_wandb: 'cstein06/control/pointmass-easy-default-clean-breeze-368-final:v0'
checkpoint_wandb: 'cstein06/control/pointmass-easy-default-desert-bird-388-final:v0'
checkpoint_filename: 'final.pt'
checkpoint_local: false

task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 4 #8

# logging
wandb_project: control
wandb_entity: cstein06
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
bin_size: ???
