defaults:
    - override hydra/launcher: submitit_local

# environment
# task: dog-run
task: humanoid-walk
# task: reacher-hard
# task: pointmass-mine
# task: walker-run

device: cuda
# device: mps


# evaluation
checkpoint: ???
eval_episodes: 3
eval_freq: 2500
num_videos: 3

# training
# steps: 10_000_000
steps: 50_000
updates_per_step: 1.
batch_size: 512
lr_factor: false
consistency_coef: 20
rho: 0.5
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: false
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 10
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# fixed eval run
# init_state: [-0.2, -0.2,  0.,  0.]

fixed_init_state: false
# init_state: [-0.2, 0.,  0.,  0.]
# init_state: [-6.5718e-02,  1.0660e+00, -3.1450e-01, -8.1257e-02, -6.2933e-01,
#          3.9723e-01, -3.5721e-01, -9.1224e-01, -8.8007e-01,  2.3683e-01,
#          1.0688e+00, -1.6105e+00, -5.2349e+00,  3.6990e+00,  3.0214e-01,
#         -2.0472e-03, -7.0046e-01,  1.8839e+00]

# init_obs: [ 9.7313e-01, -2.3024e-01,  9.2052e-01, -3.9068e-01,  9.2715e-01,
#          3.7470e-01,  9.9999e-01,  4.9157e-03,  9.9222e-01,  1.2452e-01,
#          5.4228e-01,  8.4020e-01,  8.4209e-02,  9.9645e-01,  1.2196e+00,
#          3.5098e-01,  1.0451e+00, -1.6848e+00, -4.7636e+00,  2.4429e+00,
#          9.6149e-01, -1.4970e-03, -1.4201e+00, -1.3856e+01]

# target: [0.1, 0.1] # ang, radius
# target: [0., 0.1] # x, y
target: [0.2, 0.2] # x, y

friction: 0. # not sure this works. change 'damping' in pointmass.xml

target_size: 0.02
target_margin: 0.3 #0.3
control_cost: .5 #0.1
target_reward: 1.
control_norm_thres: 0. #0.4

terminate_at_target: false #true
target_end_dist: 0.02
# target_margin: 0. 
end_reward: null

# critic # not sure this is used
num_bins: 101
vmin: -10
vmax: +10

# architecture
# model_size: 0
# use_simnorm: true #false

# for expert
model_size: 5
use_simnorm: true

no_enc: false
# no_enc: false
num_enc_layers: 2
enc_dim: 256

action_repeat: 2


################ pre train ######## 

perturb: false
perturb_steps: -1
perturb_scale: null
perturb_ang: null
action_noise: 0.1
action_skip: 0
obs_noise: 0.

force_field: false
force_field_scale: 5.

action_limit: true

# control
seed_steps: 2500
control: false 
ctrl_mse: false
ctrl_horizon: 10

lr_ctrl_pi: 0. #1e-4
lr_ctrl_dyn: 5e-4
pi_lr: 3e-4
dyn_lr: 3e-4
lr: 3e-4
reward_coef: 0.1
value_coef: 0.1
train_agent: false #true
seed_random: false
ctrl_opt: adam
init_noise: 0.2

episode_length: 200

#################################

# # # relearn ctrl dynamics
# perturb: true
# perturb_steps: 2000
# perturb_scale: 0.4
# perturb_ang: 4
# action_noise: 0.
# action_skip: 0
# obs_noise: 0.

# force_field: false
# force_field_scale: 5.

# action_limit: true

# # control
# seed_steps: 500
# control: true 
# ctrl_mse: true
# ctrl_horizon: 10

# lr_ctrl_pi: 0. #1e-4
# lr_ctrl_dyn: 0. #5e-4
# pi_lr: 0.
# dyn_lr: 3e-4
# lr: 0.
# reward_coef: 0.
# value_coef: 0.
# train_agent: true
# seed_random: false
# ctrl_opt: adam
# init_noise: 0.2

# episode_length: 200

########### perturbation test ###########

# perturb: true
# perturb_steps: 10000
# perturb_scale: 0.4 #[1., 1.] #0.5  
# perturb_ang: null #-0.8 # 1. is 90 degrees
# action_noise: 0. # 0.1
# action_skip: 0 # 20
# obs_noise: 0. # 0.01

# force_field: false
# # force_field_scale: 5.

# action_limit: true

# episode_length: 200

# # control
# seed_steps: 500
# control: true
# # control: false
# ctrl_mse: true #false
# ctrl_horizon: 10

# lr_ctrl_pi: 0.3e-4
# ctrl_opt: adam
# lr_ctrl_dyn: 0.
# pi_lr: 0.
# lr: 0.
# dyn_lr: 0.
# reward_coef: 0.1
# value_coef: 0.1
# train_agent: false
# seed_random: false
# init_noise: 0.

########################

ctrl_sig_init: 0.02
# lr_ctrl_dyn_hidden: 1e-5
# lr_ctrl_dyn_last: 10e-5
# ctrl_update_steps: 10

num_ctrl_layers: 2
ctrl_dim: 512

mlp_dim: 512
latent_dim: 512
# latent_dim: 4

action_arrow_scale: 0.25 #0.04
dist_range: 100

checkpoint_wandb: false
# checkpoint_wandb: 'cstein06/control/pointmass-easy-default-bumbling-hill-414-final:v0'
# checkpoint_wandb: 'cstein06/control/pointmass-mine-default-dry-pine-448-final:v0'
# checkpoint_wandb: 'cstein06/control/walker-run-default-graceful-water-610-final:v0'
checkpoint_filename: 'final.pt'

# checkpoint_local: false
# checkpoint_local: 'artifacts/walker-run-1.pt'
checkpoint_local: 'artifacts/humanoid-walk-1.pt'

task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: control
wandb_entity: cstein06
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
bin_size: ???
